import type {Metadata} from "next";
import {Geist, Geist_Mono, Orbitron} from "next/font/google";
import "./globals.css";
import {TaskProvider} from './_components/tasks/context/TaskProvider';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const orbitron = Orbitron({
    subsets: ['latin'],
    variable: '--font-orbitron',
    weight: ['400', '500', '700'], // можно изменить под нужный стиль
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

//
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} antialiased`}
        >
        <TaskProvider>
            {children}
        </TaskProvider>
        </body>
        </html>
    );
}
